export const ROUTES = {
  home: "/",
  danhSachNhaChoThue: "/danh-sach-nha-cho-thue",
  chiTietTinDang: (id: string) => `/chi-tiet-tin-dang/${id}`,
  dangNhap: "/dang-nhap",
  dangKy: "/dang-ky",
  tinDangCuaToi: "/tin-dang-cua-toi",
  suaTinDang: (id: string) => `/tin-dang-cua-toi/${id}/chinh-sua`,
  dangTin: "/dang-tin",
  thuVienAnh: "/thu-vien-anh",
  yeuThich: "/yeu-thich",
  quanTri: "/quan-tri",
  quanTriTinDang: "/quan-tri/tin-dang",
  quanTriNguoiDung: "/quan-tri/nguoi-dung",
  quanTriThongKe: "/quan-tri/thong-ke",
  quanTriLoaiBatDongSan: "/quan-tri/loai-bat-dong-san",
} as const;
