export const ROUTES = {
  home: "/",
  danhSachNhaChoThue: "/danh-sach-nha-cho-thue",
  chiTietTinDang: (id: string) => `/chi-tiet-tin-dang/${id}`,
  dangNhap: "/dang-nhap",
  dangKy: "/dang-ky",
  tinDangCuaToi: "/tin-dang-cua-toi",
  suaTinDang: (id: string) => `/tin-dang-cua-toi/${id}/chinh-sua`,
  dangTin: "/dang-tin",
  thuVienAnh: "/thu-vien-anh",
  yeuThich: "/yeu-thich",
  taiKhoan: "/tai-khoan",
  troGiup: "/tro-giup",
  quanTri: "/quan-tri",
  quanTriTinDang: "/quan-tri/tin-dang",
  quanTriNguoiDung: "/quan-tri/nguoi-dung",
  quanTriThongKe: "/quan-tri/thong-ke",
  quanTriLoaiBatDongSan: "/quan-tri/loai-bat-dong-san",
  quanTriBaoCao: "/quan-tri/bao-cao",
  thongTinThiTruong: "/thong-tin-thi-truong",
  chiTietTinTuc: (slug: string) => `/thong-tin-thi-truong/${slug}`,
  quanTriTinTuc: "/quan-tri/tin-tuc",
  quanTriTinTucTaoMoi: "/quan-tri/tin-tuc/tao-moi",
  quanTriTinTucSua: (id: number | string) => `/quan-tri/tin-tuc/${id}/chinh-sua`,
} as const;
