"""them_phuong_xa_moi_va_anh_xa

Revision ID: 1e3671e3f8b9
Revises: e4ba8b47958f
Create Date: 2026-08-08 11:36:34.252512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3671e3f8b9'
down_revision = 'e4ba8b47958f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phuong_xa_moi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('ma_hanh_chinh', sa.String(length=20), nullable=False),
    sa.Column('tinh_thanh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tinh_thanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_hanh_chinh')
    )
    op.create_table('phuong_xa_anh_xa',
    sa.Column('phuong_xa_id', sa.Integer(), nullable=False),
    sa.Column('phuong_xa_moi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phuong_xa_id'], ['phuong_xa.id'], ),
    sa.ForeignKeyConstraint(['phuong_xa_moi_id'], ['phuong_xa_moi.id'], ),
    sa.PrimaryKeyConstraint('phuong_xa_id', 'phuong_xa_moi_id')
    )
    op.add_column('phuong_xa', sa.Column('ma_hanh_chinh', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_phuong_xa_ma_hanh_chinh', 'phuong_xa', ['ma_hanh_chinh'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_phuong_xa_ma_hanh_chinh', 'phuong_xa', type_='unique')
    op.drop_column('phuong_xa', 'ma_hanh_chinh')
    op.drop_table('phuong_xa_anh_xa')
    op.drop_table('phuong_xa_moi')
    # ### end Alembic commands ###
