"""them_ghi_chu_xu_ly_bao_cao

Revision ID: 8808eed282b9
Revises: f2c9d1e7a3b5
Create Date: 2026-08-14 14:00:31.767115
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8808eed282b9'
down_revision = 'f2c9d1e7a3b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bao_cao', sa.Column('ghi_chu_xu_ly', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bao_cao', 'ghi_chu_xu_ly')
    # ### end Alembic commands ###
