"""khoi tao schema

Revision ID: db6b3afc131f
Revises: 
Create Date: 2026-07-29 20:36:24.812500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6b3afc131f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_bat_dong_san',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('mo_ta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=255), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=True),
    sa.Column('vai_tro', sa.Enum('NGUOI_DUNG', 'QUAN_TRI', name='vai_tro_nguoi_dung', native_enum=False, length=20), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_XAC_MINH', 'HOAT_DONG', 'BI_KHOA', name='trang_thai_nguoi_dung', native_enum=False, length=20), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ngay_cap_nhat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nguoi_dung_email'), 'nguoi_dung', ['email'], unique=True)
    op.create_table('tien_ich',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('tinh_thanh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('quan_huyen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('tinh_thanh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tinh_thanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phuong_xa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('quan_huyen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quan_huyen_id'], ['quan_huyen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tin_dang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=150), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=False),
    sa.Column('gia_thue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dien_tich', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('dia_chi_chi_tiet', sa.String(length=255), nullable=False),
    sa.Column('loai_bat_dong_san_id', sa.Integer(), nullable=False),
    sa.Column('phuong_xa_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dang_id', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_lien_he', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai_lien_he', sa.String(length=20), nullable=False),
    sa.Column('phuong_thuc_lien_he_uu_tien', sa.Enum('GOI_DIEN', 'NHAN_TIN', name='phuong_thuc_lien_he', native_enum=False, length=20), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_DUYET', 'DA_DUYET', 'BI_KHOA', 'AN', 'DA_XOA', name='trang_thai_tin_dang', native_enum=False, length=20), nullable=False),
    sa.Column('ly_do_khoa', sa.String(length=255), nullable=True),
    sa.Column('luot_xem', sa.Integer(), nullable=False),
    sa.Column('ngay_dang', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ngay_cap_nhat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loai_bat_dong_san_id'], ['loai_bat_dong_san.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dang_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['phuong_xa_id'], ['phuong_xa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bao_cao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tin_dang_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_bao_cao_id', sa.Integer(), nullable=False),
    sa.Column('ly_do', sa.String(length=150), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Enum('CHO_XU_LY', 'DA_XU_LY', name='trang_thai_bao_cao', native_enum=False, length=20), nullable=False),
    sa.Column('nguoi_xu_ly_id', sa.Integer(), nullable=True),
    sa.Column('ngay_bao_cao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ngay_xu_ly', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_bao_cao_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['nguoi_xu_ly_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['tin_dang_id'], ['tin_dang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hinh_anh_tin_dang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tin_dang_id', sa.Integer(), nullable=False),
    sa.Column('duong_dan_anh', sa.String(length=500), nullable=False),
    sa.Column('thu_tu_hien_thi', sa.Integer(), nullable=False),
    sa.Column('la_anh_dai_dien', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tin_dang_id'], ['tin_dang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tin_dang_tien_ich',
    sa.Column('tin_dang_id', sa.Integer(), nullable=False),
    sa.Column('tien_ich_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tien_ich_id'], ['tien_ich.id'], ),
    sa.ForeignKeyConstraint(['tin_dang_id'], ['tin_dang.id'], ),
    sa.PrimaryKeyConstraint('tin_dang_id', 'tien_ich_id')
    )
    op.create_table('tin_yeu_thich',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('tin_dang_id', sa.Integer(), nullable=False),
    sa.Column('ngay_luu', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['tin_dang_id'], ['tin_dang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id', 'tin_dang_id', name='uq_nguoi_dung_tin_dang_yeu_thich')
    )
    # ### end Alembic commands ###

    # Seed dữ liệu tra cứu (khớp yêu cầu đề bài & form đăng tin)
    loai_bat_dong_san = sa.table(
        'loai_bat_dong_san',
        sa.column('ten', sa.String),
        sa.column('mo_ta', sa.String),
    )
    op.bulk_insert(
        loai_bat_dong_san,
        [
            {'ten': 'Phòng trọ', 'mo_ta': 'Phòng cho thuê trong nhà trọ, khép kín hoặc chung chủ'},
            {'ten': 'Căn hộ', 'mo_ta': 'Căn hộ chung cư hoặc căn hộ dịch vụ'},
            {'ten': 'Nhà nguyên căn', 'mo_ta': 'Thuê nguyên căn nhà, không chung chủ'},
        ],
    )

    tien_ich = sa.table(
        'tien_ich',
        sa.column('ten', sa.String),
    )
    op.bulk_insert(
        tien_ich,
        [
            {'ten': 'WiFi miễn phí'},
            {'ten': 'Chỗ đậu xe'},
            {'ten': 'Thang máy'},
            {'ten': 'Bảo vệ 24/7'},
            {'ten': 'Nội thất cơ bản'},
            {'ten': 'Máy lạnh'},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tin_yeu_thich')
    op.drop_table('tin_dang_tien_ich')
    op.drop_table('hinh_anh_tin_dang')
    op.drop_table('bao_cao')
    op.drop_table('tin_dang')
    op.drop_table('phuong_xa')
    op.drop_table('quan_huyen')
    op.drop_table('tinh_thanh')
    op.drop_table('tien_ich')
    op.drop_index(op.f('ix_nguoi_dung_email'), table_name='nguoi_dung')
    op.drop_table('nguoi_dung')
    op.drop_table('loai_bat_dong_san')
    # ### end Alembic commands ###
