"""them_tin_dang_ban_cho

Revision ID: df1302576e8c
Revises: b7d3e9c1a2f4
Create Date: 2026-09-06 14:27:17.347745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1302576e8c'
down_revision = 'b7d3e9c1a2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tin_dang_ban_cho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tin_dang_id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=150), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=False),
    sa.Column('gia_thue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dien_tich', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('phong_ngu', sa.Integer(), nullable=False),
    sa.Column('phong_tam', sa.Integer(), nullable=False),
    sa.Column('dia_chi_chi_tiet', sa.String(length=255), nullable=False),
    sa.Column('loai_bat_dong_san_id', sa.Integer(), nullable=False),
    sa.Column('phuong_xa_id', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_lien_he', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai_lien_he', sa.String(length=20), nullable=False),
    sa.Column('phuong_thuc_lien_he_uu_tien', sa.Enum('GOI_DIEN', 'NHAN_TIN', name='phuong_thuc_lien_he', native_enum=False, length=20), nullable=False),
    sa.Column('tien_ich_ten', sa.JSON(), nullable=False),
    sa.Column('hinh_anh', sa.JSON(), nullable=False),
    sa.Column('ngay_gui', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loai_bat_dong_san_id'], ['loai_bat_dong_san.id'], ),
    sa.ForeignKeyConstraint(['phuong_xa_id'], ['phuong_xa.id'], ),
    sa.ForeignKeyConstraint(['tin_dang_id'], ['tin_dang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tin_dang_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tin_dang_ban_cho')
    # ### end Alembic commands ###
