"""them_phong_ngu_phong_tam

Revision ID: e4ba8b47958f
Revises: db6b3afc131f
Create Date: 2026-08-04 13:57:33.010543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ba8b47958f'
down_revision = 'db6b3afc131f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tin_dang', sa.Column('phong_ngu', sa.Integer(), nullable=False))
    op.add_column('tin_dang', sa.Column('phong_tam', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tin_dang', 'phong_tam')
    op.drop_column('tin_dang', 'phong_ngu')
    # ### end Alembic commands ###
